title: Aparat
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog


# Build settings
plugins:
  - jekyll-feed


collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      
# github pages stuff
lsi: false
safe: true
source: dataphil.github.io-main
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

domain: dataphil.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://dataphil.github.io  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder   
